### ISSUE TITLE
publish commands not work

### ISSUE THREAD

**Issue by mohammad-y** [overtrue/laravel-follow#61]
hello

When executing the publish command, it only writes:
Publishing complete

But the files are not added

**Comment by overtrue** [comment]
windows?

**Comment by lukadriel7** [comment]
Using php artisan vendor:publish then selecting the Provider Overtrue fixes the issue. It seems there is no migration tag associated with the package.

**Comment by cybercrowd** [comment]
Try using double quotes **" "** instead of single quotes when publishing. This should help especially on window machines.
```
php artisan vendor:publish --provider="Overtrue\LaravelFollow\FollowServiceProvider" --tag="config"
php artisan vendor:publish --provider="Overtrue\LaravelFollow\FollowServiceProvider" --tag="migrations"
```
Also note when you publish migrations the following file is copied to you migrations directory
`2018_06_29_032244_create_laravel_follow_tables.php`
So you may need to scroll to '2018_*' migrations to file the file. Else go to the vendor/overtune directory and copy the **migrations** directory under **database** into the same directory as **config** and re-run the command. This should work.

**Comment by ig-89** [comment]
> Try using double quotes **" "** instead of single quotes when publishing. This should help especially on window machines.
> 
> ```
> php artisan vendor:publish --provider="Overtrue\LaravelFollow\FollowServiceProvider" --tag="config"
> php artisan vendor:publish --provider="Overtrue\LaravelFollow\FollowServiceProvider" --tag="migrations"
> ```
> Also note when you publish migrations the following file is copied to you migrations directory
> `2018_06_29_032244_create_laravel_follow_tables.php`
> So you may need to scroll to '2018_*' migrations to file the file. Else go to the vendor/overtrue/laravel-follow directory and copy the **migrations** directory under **database** into the same directory as **config** and re-run the command. This should work.

Thanks for that! Double quotes worked.
