### ISSUE TITLE
n+1 problem

### ISSUE THREAD

**Issue by Livijn** [overtrue/laravel-follow#70]
I am loading a list of items that has the `CanBeFavorited` trait. I am also loading the authed users favorites with `auth()->user()->load('favorites')`. However, the `hasFavorited($item)` is not using the already loaded relationship, but instead it is querying the database creating an *n+1 problem*.

A possible solution would be to check in the `hasFavorited` if the relation is already loaded, using `relationLoaded('favorites')`, then use that.

**Comment by Livijn** [comment]
Something like this should work (haven't tried):

```
public function hasFavorited($target, $class = __CLASS__)
 {
    return $this->relationLoaded('favorites') 
        ? $this->favorites->where('pivot.followable_id', $target->id)
            ->where('followable_model', get_class($target))
            ->count()
        : Follow::isRelationExists($this, 'favorites', $target, $class);
}
````

**Comment by overtrue** [comment]
@Livijn @xsaad67 Fixed.

**Comment by xsaad67** [comment]
Hy thanks for the response but how do I call the **upvoters** relationship on eager loading? Like `Post::with("upvoters")->get();` ?

**Comment by rdgout** [comment]
Hi @overtrue 

When I use the loaded relation the morph gets a User model. However the `relationKey` checks for `user_id` whilst the User model usually contains a `id` field. 
That way, the entire new if check never gets any results.

Can you fix this?

Reproducing is easy:

Create 2 user models
Follow user 1 from user 2
Follow user 2 from user 1
Fetch user 2 whilst eager loading the `followings` and `followers`
Check the result for `isFollowedBy` and `isFollowing`

Both should be false since the if checks already results in an empty collection.
if the `relationKey` is 'id' it does work.

```
        if ($model->relationLoaded($relation)) {
            $relationKey = 'id';

            return $model->{$relation}->where($relationKey, head($target->ids))->isNotEmpty();
        }
```

**Comment by overtrue** [comment]
@rdgout I will check this.

**Comment by rdgout** [comment]
@overtrue 

Issue 76 has the same issue I found.

**Comment by overtrue** [comment]
@rdgout I've fixed the problem. plz take a try with new version.
