### ISSUE TITLE
Request for add config option

### ISSUE THREAD

**Issue by MoeCasts** [overtrue/laravel-follow#83]
As the relation types conflict with other packages, I have to change the relation types name to use the package. I modified the code, but there is a question now,  when you update the package, I must to modified the code again, that is unconvenient.

**Comment by alvinhu** [comment]
You should override the method instead of modify the package.

**Comment by cybercrowd** [comment]
Try using double quotes " " instead of single quotes when publishing. This should help especially on window machines.

`php artisan vendor:publish --provider="Overtrue\LaravelFollow\FollowServiceProvider" --tag="config"`

The config file can be found under  your vendor directory **/vendor/overtrue/laravel-follow/config/follow.php**
